title: Hydrogeological Field Methods
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://gw-inux.github.io/Hydrogeological-Field-Methods

aux_links:
  Template Repository: https://github.com/gw-inux/Hydrogeological-Field-Methods
